const event=(time,title,type,place,note,row,extra={})=>({time,title,type,place,note,row,...extra});
export const days=[
{date:'2026-09-25',city:'上海 → 吉隆坡',en:'THE JOURNEY BEGINS',title:'出发，去南半球',subtitle:'整理好期待，向澳洲出发。',zone:'Asia/Shanghai',offset:'+08:00',range:[8,18],events:[
event('12:30','出发前往浦东机场 T2','transit','上海浦东国际机场 T2','4 号线转 2 号线；计划耗时 1.5 小时。',12),
event(null,'值机与安检','flight','上海浦东国际机场 T2','核对证件、行李与登机口，以航空公司要求为准。',13),
event('15:25','上海 → 吉隆坡','flight','上海浦东国际机场 T2','原计划 15:25–21:00，浦东 T2 → 吉隆坡 T1。',14),
event('22:25','吉隆坡 → 墨尔本','flight','Kuala Lumpur International Airport Terminal 1','原计划次日 08:20 抵达墨尔本 T2；准备入境卡与笔。入境卡上的酒店地址需核对。',15)]},
{date:'2026-09-26',city:'墨尔本',en:'HELLO, MELBOURNE',title:'在墨尔本，慢慢着陆',subtitle:'一杯咖啡，一场海边日落。旅程从这里开始。',zone:'Australia/Melbourne',offset:'+10:00',range:[19,81],events:[
event('08:20','抵达墨尔本 · T2','flight','Melbourne Airport Terminal 2','准备护照、签证、机酒确认单、入境卡；入境后领取行李。',21),
event('10:30','搭乘 SkyBus 进入市区','transit','Southern Cross Station Melbourne','计划 10:30–11:00 到南十字星站，原表预计 35 分钟。下车后步行前往酒店。',32),
event('13:00','到酒店，寄存行李','hotel','Oaks Melbourne on William Suites','墨尔本威廉姆街盛橡套房酒店。原表 15:00 入住、11:00 离店；提前入住需酒店确认。',36),
event(null,'午餐 · Operator25 与备选','food','Operator25 Melbourne','首选 Operator25：软壳蟹煎蛋、紫薯华夫饼。备选 Snow Monkey Ramen、Phở Tùng、Pho Thin 等，完整菜单见原计划。',43),
event(null,'咖啡与可颂的小停留','food','Overlay Coffee Melbourne','Overlay 花生酱拿铁；Lune 杏仁可颂。按当天精力选择。',51),
event(null,'办理入住，休息一下','hotel','Oaks Melbourne on William Suites','收拾行李、洗澡、换装。原表入住时间为 15:00，未给此项具体安排时间。',57),
event('16:40','向 St Kilda 海边出发','transit','St Kilda Pier Melbourne','原计划 16:40–17:00。电车或打车，具体交通路线需出发时核对。',61),
event('17:00','St Kilda Pier · 看海与日落','spot','St Kilda Pier Melbourne','海边拍照，记得带外套。原表日落时间未核实。企鹅场次 18:30 / 19:30 与晚餐可能冲突。',64),
event(null,'企鹅归巢 · 可选活动','spot','St Kilda Pier Melbourne','表内记录两场 18:30–19:30 / 19:30–20:30，需预约并与晚餐二选一。',65,{optional:true}),
event('19:00','晚餐 · Max on Hardware','food','Max on Hardware Melbourne','原表标注 19:00 预约、无取消政策。推荐袋鼠肉、五花肉、海鲜烩饭；以实际确认单为准。',70),
event(null,'超市补给，回酒店','shop','Coles Melbourne CBD','买水、牛奶、酸奶与零食；伴手礼主要留在悉尼采购。',75)]},
{date:'2026-09-27',city:'墨尔本',en:'WANDER THE CITY',title:'把城市，走成风景',subtitle:'从热闹市场到安静画廊，收藏墨尔本的日常。',zone:'Australia/Melbourne',offset:'+10:00',range:[82,159],events:[
event(null,'维多利亚女王市场','spot','Queen Victoria Market Melbourne','步行约 850 米，途经 Flagstaff Gardens。青口贝、澳白、果酱甜甜圈、德国热狗按喜好选择。',88),
event(null,'维多利亚州立图书馆','spot','State Library Victoria','先到 6 楼看全景，再去 5 楼与 3 楼拍摄；途经 Melbourne Central。',116),
event(null,'唐人街 → 皇家拱廊','spot','Royal Arcade Melbourne','路过唐人街和 ChaTraMue，皇家拱廊拍照后前往市政厅。',120),
event(null,'市政厅、涂鸦街与福林德车站','spot','Flinders Street Station Melbourne','经过圣保罗大教堂、Hosier Lane、联邦广场；教堂对面的长椅可拍车站。',129),
event(null,'维多利亚国家美术馆','spot','National Gallery of Victoria','原表记录 10:00–17:00，留意闭馆时间；拍摄 2 楼作品及雕塑花园。',142),
event('18:45','晚餐 · Palermo','food','Palermo Melbourne','原表有预约编号；眼肉牛排、脆土豆、提拉米苏。取消规则在原表中有不同表述，请以确认单为准。',149),
event(null,'回酒店 · 检查后续预订','hotel','Oaks Melbourne on William Suites','核对行李额、Hello Auntie 预订、Kiama 包车日期与天气。',155)]},
{date:'2026-09-28',city:'大洋路',en:'THE GREAT OCEAN ROAD',title:'一路向海，追着风走',subtitle:'十二门徒、悬崖与海湾，今天交给海岸线。',zone:'Australia/Melbourne',offset:'+10:00',range:[160,197],events:[
event('07:50','Atlantis Hotel 集合出发','transit','Atlantis Hotel Melbourne','反向一日团；表内出发时间 07:50（另写 07:00–08:00），以旅行社通知为准。带保暖衣物、零食、充电宝及现金。',167),
event('09:30','Colac 小镇休息','spot','Colac Victoria','服务区停留约 15 分钟。',170),
event('11:00','十二门徒 · 海岸高光','spot','Twelve Apostles Victoria','预计停留 60 分钟。Gibson Steps 为可选，步行往返紧张，跟随团队安排。',171),
event('12:10','洛克阿德峡谷与沉船湾','spot','Loch Ard Gorge Victoria','原计划约 30 分钟，观景台与 The Razorback。',174),
event('13:30','寻找野生考拉','spot',null,'团队沿途停留约 15 分钟，是否遇到取决于当天情况。',175),
event('13:50','Apollo Bay · 自由午餐','food','Apollo Bay Victoria','约 60 分钟。海鲜拼盘或海鲜意面，饭后可选 Dooley’s 冰淇淋。',177),
event('15:15','Light-Cradling Nook','spot',null,'原表中的沿途停留点，具体地点由旅行社确认。',183),
event('16:15','大洋路纪念门牌','spot','Great Ocean Road Memorial Arch','约 10 分钟拍照。',184),
event('16:40','小红帽灯塔','spot',null,'原表记录停留 30 分钟；具体灯塔地点及登塔费用请随团确认。',185),
event('19:50','返回墨尔本，晚餐自选','food','Melbourne CBD','预计 19:30–20:00 回城。Phở Tùng 在原表中写周一休息，今天为周一，建议另选 BBQ King 或 Chickorea。',186),
event(null,'整理行李、备份相机','hotel',null,'注意行李重量与分类。',194)]},
{date:'2026-09-29',city:'墨尔本',en:'A LITTLE ROOM TO WANDER',title:'留一天，给自由发挥',subtitle:'不赶路的日子，也属于旅行。',zone:'Australia/Melbourne',offset:'+10:00',range:[198,217],events:[
event(null,'墨尔本自由行 · 待定','spot','Melbourne','详细计划尚未填写；原表提到可能直接前往悉尼，汇总表仍为 9 月 30 日飞悉尼。请核对机票后补充。',198)]},
{date:'2026-09-30',city:'墨尔本 → 悉尼',en:'NEXT STOP, SYDNEY',title:'你好，海港之城',subtitle:'从一座喜欢的城市，飞往另一种浪漫。',zone:'Australia/Sydney',offset:'+10:00',range:[218,290],events:[
event('08:00','起床，整理行李','hotel',null,'收拾行李、检查随身行李和托运行李额度。',220),
event('09:00','前往墨尔本机场','transit','Melbourne Airport Terminal 4','从南十字星站乘 SkyBus。原计划 10:00 到机场。',223),
event('10:00','T4 值机与行李托运','flight','Melbourne Airport Terminal 4','检查捷星行李额。原表“提前 1.5min”疑似笔误，请按航空公司规定办理值机。',225),
event('11:30','JQ514 · 墨尔本 → 悉尼','flight','Melbourne Airport Terminal 4','原计划 11:30–13:00，墨尔本 T4 → 悉尼 T2。航班信息以航空公司为准。',230),
event('15:00','悉尼机场 → 市区','transit','Museum Station Sydney','原表写 T2 抵达但列出 International Airport Station，站名需要核对；不要直接按国际机场站导航。',239),
event('15:30','到酒店，办理入住','hotel',null,'详细表：Song Hotel；汇总表：悉尼海港套房酒店。请先核对酒店，地址确认前暂不提供导航。',243),
event('16:15','Market City · 逛逛伴手礼','shop','Market City Sydney','步行约 1 公里。若落地晚，可以选达令港轻松路线。',250),
event('17:20','Plan A · 天文台看风景','spot','Observatory Hill Park Sydney','原计划 17:20–17:40。与 Plan B 二选一；日落时间待核实。',256,{optional:true}),
event('17:20','Plan B · 达令港散步','spot','Darling Harbour Sydney','落地较晚时选择较轻松的路线，与 Plan A 二选一。',270,{optional:true}),
event('18:30','晚餐 · Hello Auntie','food','Hello Auntie Darling Square','原表记录提前 24 小时免费取消，否则每人 25 澳元。牛肉塔塔、春卷、鸭肉意面和咖啡甜品。',276),
event(null,'超市补给，确认明日包车','shop','Coles World Square Sydney','准备零食、查看司机信息、备份相机。',279)]},
{date:'2026-10-01',city:'Kiama · 悉尼南线',en:'A DAY ALONG THE COAST',title:'驶入海边的油画小镇',subtitle:'白色灯塔、蓝色海浪，还有一路的好风景。',zone:'Australia/Sydney',offset:'+10:00',range:[291,374],events:[
event('07:15','起床与出发准备','hotel',null,'原表准备清单：防晒、雨伞、充电宝、现金、相机、纸巾、零食和大购物袋。',295),
event('08:15','酒店早餐','food',null,'预留至 08:45，准时与包车司机会合。',296),
event('08:45','南线包车出发','transit',null,'确认司机与集合地点，前往 Bald Hill。',299),
event('09:45','Bald Hill 观景台','spot','Bald Hill Lookout','预计停留至 10:15；与 Sea Cliff Bridge 根据包车行程选择。',302),
event(null,'Sea Cliff Bridge · 可选','spot','Sea Cliff Bridge','原表标注可能不去，与 Bald Hill 二选一。',304,{optional:true}),
event(null,'午餐 · Kiama / 卧龙岗','food','Kiama NSW','原计划有卧龙岗炸鸡与 Kiama 午餐备选，随当天路线安排。',308),
event('12:00','Kiama 灯塔与喷水洞','spot','Kiama Blowhole','预计至 13:00。灯塔与喷水洞在一起，喷水效果受海况影响。',323),
event('13:15','Gerringong · 童话公路','spot','Gerringong Whale Watching Platform','沿 Tasman Drive 漫步，预计至 14:10。尊重当地居民，保持安静。',329),
event(null,'袋鼠谷 · 加价备选','spot','Bendeela Recreation Area','原表写需要另加费用；未确认加入当天行程。',331,{optional:true}),
event('14:30','Minnamurra · 心形沙滩','spot','Minnamurra Lookout','预计停留 30 分钟。',335),
event('15:00','返回悉尼 · QVB 购物','shop','Queen Victoria Building Sydney','原计划 16:30 回到 QVB，附近 Aesop、Lululemon 等按需要购买；购物清单见原备注。',337),
event('19:45','晚餐 · Bar Totti’s','food',"Bar Totti's Sydney",'原表记录提前 2 小时取消，否则每人 50 澳元。烤饼、Burrata、火腿与提拉米苏。',356),
event(null,'买伴手礼，整理行李','shop','Coles World Square Sydney','备份照片、整理发票与行李。',363)]},
{date:'2026-10-02',city:'悉尼',en:'POSTCARDS FROM SYDNEY',title:'把悉尼，装进相机里',subtitle:'歌剧院的清晨，海岸线的午后。',zone:'Australia/Sydney',offset:'+10:00',range:[375,454],events:[
event('07:30','起床 · 酒店早餐','hotel',null,'带防晒、墨镜、露营垫、拍摄设备，准备适合徒步的鞋。',378),
event('08:30','出发去 Circular Quay','transit','Circular Quay Sydney','白天拍车站、海港大桥与歌剧院；沿途可选 A.P Bakery。',380),
event(null,'悉尼歌剧院','spot','Sydney Opera House','拍照点：Opera Bar 外侧步道、Man O’War Steps、植物园 Harbour View Lawn。',393),
event(null,'麦考利夫人椅 → 美术馆','spot',"Mrs Macquarie's Chair Sydney",'从歌剧院步行约 1.4 公里；再去新南威尔士美术馆，可按兴趣调整。',395),
event(null,'圣母主教座堂与海德公园','spot',"St Mary's Cathedral Sydney",'教堂内遵守现场参观要求，海德公园喷泉和长椅可拍照。',404),
event(null,'午餐三选一，回酒店换装','food','Gumshara Sydney','Gumshara、Pork Rolls 或 Single O；备选详见原备注。',412),
event(null,'Coogee → Bondi 海岸徒步','spot','Coogee Beach Sydney','约 6 公里、2.5 小时。经过 Waverley Cemetery、Tamarama 和 Icebergs。累了可跳过徒步直接到海滩。',425),
event('17:00','Watsons Bay · 海边慢时光','spot','Robertson Park Watsons Bay','计划停留至 18:00；原表日落时间待核实。',437),
event('18:15','渡轮前往 Circular Quay','transit','Watsons Bay Wharf','计划至 18:45；原表另写 F9 最晚 15:45，与此冲突。请先核对实际渡轮班次。',439),
event('18:45','Circular Quay · 拍海港夜景','spot','Circular Quay Sydney','19:00 左右准备去餐厅，步行约 700 米。',442),
event('19:30','晚餐 · Rockpool','food','Rockpool Bar & Grill Sydney','原表记录提前 4 小时取消，否则每人 50 澳元。预约编号与点菜建议见原备注。',447),
event(null,'回酒店，备份相机','hotel',null,'整理行李，准备明日返程。',453)]},
{date:'2026-10-03',city:'悉尼 → 上海',en:'UNTIL NEXT TIME',title:'带着回忆，回家',subtitle:'最后检查一次行李，把风景留在心里。',zone:'Australia/Sydney',offset:'+10:00',range:null,events:[
event(null,'退房与机场交通 · 待补充','hotel',null,'原表未提供详细安排；请补充酒店确认单、航班号和机场集合时间。',null),
event('14:10','悉尼 → 上海 · 返程','flight','Sydney Airport','汇总表记录 14:10 起飞；航班号、航站楼、抵达时间未填写。原表机票含 20kg 行李额，以机票为准。',47,{sourceSheet:'wqGvS6'})]}
];
days.forEach((d,i)=>{d.number=i;d.events.forEach((e,j)=>e.id=`${d.date}-${j}`)});
export const issues=[
{title:'悉尼酒店名称不一致',text:'汇总表是“悉尼海港套房酒店”，9/30 详细计划是“Song Hotel”。请按实际确认单核对。',date:'09.30'},
{title:'企鹅与晚餐的时间冲突',text:'9/26 企鹅场次为 18:30 或 19:30，当晚 Max on Hardware 预约为 19:00，需要选择。',date:'09.26'},
{title:'9 月 29 日安排待定',text:'详细表保留自由行或提前飞悉尼两种想法；汇总表与航班明细都是 9/30 飞悉尼。',date:'09.29'},
{title:'渡轮班次需要核对',text:'10/2 计划 18:15 搭船，但备注又写 F9 最晚 15:45。不要将该时间当作已确认班次。',date:'10.02'},
{title:'墨尔本酒店地址混用',text:'入境卡备注写 Dorsett Melbourne，住宿计划写威廉姆街盛橡。请用真实入住酒店信息。',date:'09.25'},
{title:'机场站名与航站楼不符',text:'9/30 抵达悉尼 T2，但市区交通写 International Airport Station；请核对实际车站。',date:'09.30'},
{title:'周一晚餐备选需调整',text:'9/28 为周一，Phở Tùng 的原表备注也写周一休息。可另选原表中的餐厅。',date:'09.28'},
{title:'日落、营业时间与预订待确认',text:'这里展示的是你的计划快照，未在线核实日落、营业时间、票价或取消条款。按实际预订和出发当天信息安排。',date:'全程'}
];
