// Generated by scripts/import-guide-media.mjs; stable event IDs override place research.
export const userByEvent = {
  "2026-09-26-3": {
    "sourceLabel": "你的餐厅笔记",
    "photos": [
      {
        "src": "/guide-media/user-food-E7.jpg",
        "caption": "午餐 · Operator25 · 你的参考图 1",
        "kind": "reference"
      },
      {
        "src": "/guide-media/user-food-F7.jpg",
        "caption": "午餐 · Operator25 · 你的参考图 2",
        "kind": "reference"
      },
      {
        "src": "/guide-media/user-food-G7.jpg",
        "caption": "午餐 · Operator25 · 你的参考图 3",
        "kind": "reference"
      }
    ],
    "dishes": [
      "牛肉班尼迪克蛋",
      "Beef Bulgogi Taco",
      "Singapore Chilli Crab Omelette",
      "Mont Verte"
    ],
    "recommendationNote": "流心蛋+牛肉+面包，荷兰酱带一点甜口，吃着很舒服",
    "itineraryNote": "12:00 预约；11:45 从酒店步行出发。其他餐厅仅作备选。"
  },
  "2026-09-26-4": {
    "sourceLabel": "你的餐厅笔记",
    "photos": [
      {
        "src": "/guide-media/user-food-G8.jpg",
        "caption": "咖啡与可颂的小停留 · 你的参考图 1",
        "kind": "reference"
      }
    ],
    "dishes": [
      "Almond Croissant · 杏仁可颂"
    ]
  },
  "2026-09-27-max-lunch": {
    "sourceLabel": "你的餐厅笔记",
    "photos": [
      {
        "src": "/guide-media/user-food-E10.jpg",
        "caption": "午餐 · Max on Hardware · 你的参考图 1",
        "kind": "reference"
      },
      {
        "src": "/guide-media/user-food-G10.jpg",
        "caption": "午餐 · Max on Hardware · 你的参考图 2",
        "kind": "reference"
      }
    ],
    "dishes": [
      "Paella · 海鲜饭",
      "Porcellina / Mushroom Pizza",
      "Char Grill Kangaroo"
    ]
  },
  "2026-09-30-9": {
    "sourceLabel": "你的餐厅笔记",
    "photos": [
      {
        "src": "/guide-media/user-food-E16.jpg",
        "caption": "晚餐 · Hello Auntie · 你的参考图 1",
        "kind": "reference"
      },
      {
        "src": "/guide-media/user-food-G16.jpg",
        "caption": "晚餐 · Hello Auntie · 你的参考图 2",
        "kind": "reference"
      }
    ],
    "dishes": [
      "炭烤羊臀肉",
      "Lobster Wonton · 龙虾馄饨",
      "提拉米苏"
    ]
  },
  "2026-09-26-7": {
    "sourceLabel": "你的拍照笔记",
    "photos": [
      {
        "src": "/guide-media/user-spot-G7.jpg",
        "caption": "St Kilda Pier · 看海与日落 · 你的参考图 1",
        "kind": "reference"
      },
      {
        "src": "/guide-media/user-spot-H7.jpg",
        "caption": "St Kilda Pier · 看海与日落 · 你的参考图 2",
        "kind": "reference"
      },
      {
        "src": "/guide-media/user-spot-I7.jpg",
        "caption": "St Kilda Pier · 看海与日落 · 你的参考图 3",
        "kind": "reference"
      }
    ]
  },
  "2026-09-27-1": {
    "sourceLabel": "你的拍照笔记",
    "photos": [
      {
        "src": "/guide-media/user-spot-G10.jpg",
        "caption": "维多利亚州立图书馆 · 你的参考图 1",
        "kind": "reference"
      },
      {
        "src": "/guide-media/user-spot-H10.jpg",
        "caption": "维多利亚州立图书馆 · 你的参考图 2",
        "kind": "reference"
      }
    ]
  },
  "2026-09-27-3": {
    "sourceLabel": "你的拍照笔记",
    "photos": [
      {
        "src": "/guide-media/user-spot-G12.jpg",
        "caption": "市政厅、涂鸦街与福林德车站 · 你的参考图 1",
        "kind": "reference"
      },
      {
        "src": "/guide-media/user-spot-H12.jpg",
        "caption": "市政厅、涂鸦街与福林德车站 · 你的参考图 2",
        "kind": "reference"
      }
    ]
  },
  "2026-09-27-4": {
    "sourceLabel": "你的拍照笔记",
    "photos": [
      {
        "src": "/guide-media/user-spot-F13.jpg",
        "caption": "维多利亚国家美术馆 · 你的参考图 1",
        "kind": "reference"
      },
      {
        "src": "/guide-media/user-spot-G13.jpg",
        "caption": "维多利亚国家美术馆 · 你的参考图 2",
        "kind": "reference"
      },
      {
        "src": "/guide-media/user-spot-H13.jpg",
        "caption": "维多利亚国家美术馆 · 你的参考图 3",
        "kind": "reference"
      }
    ]
  },
  "2026-09-28-2": {
    "sourceLabel": "你的拍照笔记",
    "photos": [
      {
        "src": "/guide-media/user-spot-F15.jpg",
        "caption": "十二门徒 · 海岸高光 · 你的参考图 1",
        "kind": "reference"
      },
      {
        "src": "/guide-media/user-spot-G15.jpg",
        "caption": "十二门徒 · 海岸高光 · 你的参考图 2",
        "kind": "reference"
      },
      {
        "src": "/guide-media/user-spot-H15.jpg",
        "caption": "十二门徒 · 海岸高光 · 你的参考图 3",
        "kind": "reference"
      },
      {
        "src": "/guide-media/user-spot-I15.jpg",
        "caption": "十二门徒 · 海岸高光 · 你的参考图 4",
        "kind": "reference"
      }
    ]
  },
  "2026-09-28-3": {
    "sourceLabel": "你的拍照笔记",
    "photos": [
      {
        "src": "/guide-media/user-spot-F16.jpg",
        "caption": "洛克阿德峡谷与沉船湾 · 你的参考图 1",
        "kind": "reference"
      }
    ]
  }
}
export const researchByPlace = {
  "Bar Totti's Sydney": {
    "photos": [
      {
        "src": "/guide-media/xhs-bar-tottis-cover.jpg",
        "caption": "门店、烤饼、Burrata 与提拉米苏拼图",
        "kind": "collage",
        "author": "箭小小",
        "sourceUrl": "https://www.xiaohongshu.com/explore/6999687c000000000a03ee55"
      }
    ],
    "suggestion": "",
    "additionalDishes": [],
    "recommendationNote": ""
  },
  "Palermo Melbourne": {
    "photos": [
      {
        "src": "/guide-media/xhs-palermo-steak.jpg",
        "caption": "炭火牛排 · 部位未标明",
        "kind": "dish",
        "author": "San Telmo Group",
        "sourceUrl": "https://www.xiaohongshu.com/explore/6a6be0520000000008009c00"
      }
    ],
    "suggestion": "",
    "additionalDishes": [],
    "recommendationNote": ""
  },
  "Rockpool Bar & Grill Sydney": {
    "photos": [
      {
        "src": "/guide-media/xhs-rockpool-steaks.jpg",
        "caption": "牛排部位对照拼图",
        "kind": "collage",
        "author": "悉尼在逃短尾矮袋鼠",
        "sourceUrl": "https://www.xiaohongshu.com/explore/69b3d920000000001a032184"
      }
    ],
    "suggestion": "",
    "additionalDishes": [
      "XO 酱烤扇贝",
      "烤虾",
      "Rump / Skirt 牛排"
    ],
    "recommendationNote": ""
  },
  "Apollo Bay Victoria": {
    "photos": [
      {
        "src": "/guide-media/xhs-apollo-seafood.jpg",
        "caption": "海鲜拼盘、意面与烤虾拼图",
        "kind": "collage",
        "author": "Abby梦想环游世界🥕",
        "sourceUrl": "https://www.xiaohongshu.com/explore/68d89787000000001203f138"
      }
    ],
    "suggestion": "",
    "additionalDishes": [
      "Seafood Cafe · 海鲜拼盘、虾仁意面"
    ],
    "recommendationNote": ""
  },
  "Kiama NSW": {
    "photos": [
      {
        "src": "/guide-media/xhs-kiama-fries.jpg",
        "caption": "肉酱薯条近景 · 笔记作者称呼",
        "kind": "dish",
        "author": "冰淇淋肉松麻薯包",
        "sourceUrl": "https://www.xiaohongshu.com/explore/69e7331900000000210396ff"
      }
    ],
    "suggestion": "",
    "additionalDishes": [
      "The Hungry Monkey · 肉酱薯条",
      "The Hungry Monkey · Bad Boy 汉堡",
      "The Hungry Monkey · Acai bowl"
    ],
    "recommendationNote": ""
  },
  "Kiama Blowhole": {
    "photos": [
      {
        "src": "/guide-media/xhs-kiama-lighthouse.jpg",
        "caption": "灯塔与草地低角度构图",
        "kind": "landscape",
        "author": "老天猫啊",
        "sourceUrl": "https://www.xiaohongshu.com/explore/6a9abbc6000000002803a967"
      }
    ],
    "suggestion": "在开放草地以灯塔为背景，人物放在塔旁，留出天空。",
    "additionalDishes": [],
    "recommendationNote": ""
  },
  "Gerringong Whale Watching Platform": {
    "photos": [
      {
        "src": "/guide-media/xhs-gerringong-street.jpg",
        "caption": "街道下坡与远处海湾",
        "kind": "landscape",
        "author": "老天猫啊",
        "sourceUrl": "https://www.xiaohongshu.com/explore/6a9abbc6000000002803a967"
      }
    ],
    "suggestion": "从人行道利用起伏街道和海湾构图，人物侧身走动。",
    "additionalDishes": [],
    "recommendationNote": ""
  },
  "Minnamurra Lookout": {
    "photos": [
      {
        "src": "/guide-media/xhs-minnamurra-coast.jpg",
        "caption": "日落时的河口沙洲",
        "kind": "landscape",
        "author": "老天猫啊",
        "sourceUrl": "https://www.xiaohongshu.com/explore/6a9abbc6000000002803a967"
      }
    ],
    "suggestion": "从观景草地拍河口、沙洲与天空，人物背影放在画面边侧。",
    "additionalDishes": [],
    "recommendationNote": ""
  },
  "Bald Hill Lookout": {
    "photos": [
      {
        "src": "/guide-media/xhs-bald-hill.jpg",
        "caption": "Bald Hill 海岸曲线",
        "kind": "landscape",
        "author": "阿牛",
        "sourceUrl": "https://www.xiaohongshu.com/explore/695655970000000022022195"
      }
    ],
    "suggestion": "从开放观景台拍摄海岸曲线，前景保留少量草地，人物侧身看海。",
    "additionalDishes": [],
    "recommendationNote": ""
  },
  "Sydney Opera House": {
    "photos": [
      {
        "src": "/guide-media/xhs-opera-pose.jpg",
        "caption": "Opera Bar 一侧长椅坐姿",
        "kind": "pose",
        "author": "婷妞的旅行日记",
        "sourceUrl": "https://www.xiaohongshu.com/explore/69d8cd35000000001a02a8f5"
      }
    ],
    "suggestion": "侧坐在长椅上，肩膀放松，头微侧向光；用椅背曲线引向歌剧院。",
    "additionalDishes": [],
    "recommendationNote": ""
  },
  "Royal Botanic Garden Sydney": {
    "photos": [
      {
        "src": "/guide-media/xhs-botanic-pose.jpg",
        "caption": "植物园滨水处站姿与海港合影",
        "kind": "pose",
        "author": "婷妞的旅行日记",
        "sourceUrl": "https://www.xiaohongshu.com/explore/69d8cd35000000001a02a8f5"
      }
    ],
    "suggestion": "站在滨水步道护栏内，身体微侧、双手自然放口袋，视线望向一旁，留出歌剧院和海港大桥。",
    "additionalDishes": [],
    "recommendationNote": ""
  },
  "Bondi Beach Sydney": {
    "photos": [
      {
        "src": "/guide-media/xhs-bondi-poses.jpg",
        "caption": "South Bondi 多种站姿参考拼图",
        "kind": "pose",
        "author": "睡美人安安",
        "sourceUrl": "https://www.xiaohongshu.com/explore/6aa7e3c40000000028003348"
      }
    ],
    "suggestion": "站在栏杆内侧，身体微侧，抬手轻扶头发或自然垂手；树木作为两边框景，海滩曲线完整留在背景。",
    "additionalDishes": [],
    "recommendationNote": ""
  },
  "St Mary's Cathedral Sydney": {
    "photos": [
      {
        "src": "/guide-media/xhs-cathedral-poses.jpg",
        "caption": "圣玛丽教堂建筑与长椅坐姿拼图",
        "kind": "pose",
        "author": "小葵",
        "sourceUrl": "https://www.xiaohongshu.com/explore/69a36c7b0000000022021bb2"
      }
    ],
    "suggestion": "在教堂旁长椅自然侧坐，双手放腿上，人物置于画面一侧，保留尖塔轮廓。",
    "additionalDishes": [],
    "recommendationNote": ""
  },
  "Art Gallery of New South Wales": {
    "photos": [
      {
        "src": "/guide-media/xhs-nsw-gallery-poses.jpg",
        "caption": "新州美术馆看画站姿与座椅坐姿",
        "kind": "pose",
        "author": "小嘟嘟📷",
        "sourceUrl": "https://www.xiaohongshu.com/explore/69a78472000000001b01cc65"
      }
    ],
    "suggestion": "在允许拍摄的展厅，侧身看画或在座椅上自然侧坐；人物与画框错开，保留画框完整边缘。",
    "additionalDishes": [],
    "recommendationNote": ""
  },
  "Gertrude Street Fitzroy Melbourne": {
    "photos": [
      {
        "src": "/guide-media/xhs-fitzroy-poses.jpg",
        "caption": "Fitzroy 街区回头与站姿拼图",
        "kind": "pose",
        "author": "Kitty酱📷",
        "sourceUrl": "https://www.xiaohongshu.com/explore/6a86ea2c000000001d01c7c1"
      }
    ],
    "suggestion": "在人行道上以复古店面为背景，侧身回头或轻扶头发；相机略低于眼睛，保留街道纵深。",
    "additionalDishes": [],
    "recommendationNote": ""
  },
  "Queen Victoria Market Melbourne": {
    "photos": [
      {
        "src": "/guide-media/xhs-queen-market-pose.jpg",
        "caption": "维妈市场橱窗旁手持咖啡站姿",
        "kind": "pose",
        "author": "here_",
        "sourceUrl": "https://www.xiaohongshu.com/explore/6a900ebd000000002003e3ed"
      }
    ],
    "suggestion": "站在橱窗侧边，手持咖啡、身体微侧、视线看向店铺；以面包陈列和窗框作背景。",
    "additionalDishes": [],
    "recommendationNote": ""
  },
  "Royal Arcade Melbourne": {
    "photos": [
      {
        "src": "/guide-media/xhs-royal-arcade-pose.jpg",
        "caption": "皇家拱廊楼梯旁回头姿势",
        "kind": "pose",
        "author": "Net_Z",
        "sourceUrl": "https://www.xiaohongshu.com/explore/690702b30000000005010f50"
      }
    ],
    "suggestion": "楼梯侧面站定，身体朝前、头轻轻回看镜头；从略高位置取景，让栏杆形成对角线。按店铺开放范围拍摄。",
    "additionalDishes": [],
    "recommendationNote": ""
  },
  "Monash University Caulfield Campus": {
    "photos": [
      {
        "src": "/guide-media/xhs-monash-caulfield.jpg",
        "caption": "Caulfield 图书馆天井对称构图",
        "kind": "architecture",
        "author": "Gimme Melbourne",
        "sourceUrl": "https://www.xiaohongshu.com/explore/6976a16a000000002103d95e"
      }
    ],
    "suggestion": "图书馆若开放可抬头拍天井的对称线条；户外回访合影可选公共休息区，在建筑线条旁自然站立。",
    "additionalDishes": [],
    "recommendationNote": ""
  },
  "Bendeela Recreation Area": {
    "photos": [
      {
        "src": "/guide-media/xhs-bendeela-wombat.jpg",
        "caption": "Bendeela 草地上的袋熊 · 观察参考",
        "kind": "landscape",
        "author": "RandallZxx",
        "sourceUrl": "https://www.xiaohongshu.com/explore/6a995dd5000000002900d72c"
      }
    ],
    "suggestion": "从开放区域用长焦或手机变焦记录袋熊与草地，保留动物周围空间；不追逐、触摸或靠近合影。",
    "additionalDishes": [],
    "recommendationNote": ""
  },
  "Great Ocean Road Memorial Arch": {
    "photos": [
      {
        "src": "/guide-media/xhs-memorial-arch-pose.jpg",
        "caption": "纪念拱门旁举手合影 · 路旁停留区",
        "kind": "pose",
        "author": "萌二biuのmax",
        "sourceUrl": "https://www.xiaohongshu.com/explore/69dc800a000000001d019716"
      }
    ],
    "suggestion": "站在路旁停留区的栏杆内，身体略侧、抬一只手作托住门牌的动作；镜头稍向上，完整保留 GREAT OCEAN ROAD 字样。",
    "additionalDishes": [],
    "recommendationNote": ""
  },
  "Melbourne CBD": {
    "photos": [
      {
        "src": "/guide-media/xhs-chickorea-chicken.jpg",
        "caption": "Chickorea · 无骨炸鸡与 Cream Onion 酱（口味评价有分歧）",
        "kind": "dish",
        "author": "肥咪日记",
        "sourceUrl": "https://www.xiaohongshu.com/explore/6a2d195b000000003502d19e"
      }
    ],
    "suggestion": "",
    "additionalDishes": [
      "Chickorea · Boneless Chicken 无骨炸鸡"
    ],
    "recommendationNote": "Chickorea：食客推荐无骨炸鸡的酥脆口感；Cream Onion 酱评价有分歧，这篇食记觉得后味偏苦，原攻略则更喜欢它，可按口味选酱。"
  },
  "St Kilda Beach Melbourne": {
    "photos": [
      {
        "src": "/guide-media/xhs-donovans-liver.jpg",
        "caption": "Donovans · Chicken Liver 鸡肝酱配面包",
        "kind": "dish",
        "author": "Evelyn-2026版🎀",
        "sourceUrl": "https://www.xiaohongshu.com/explore/67fcaf99000000001a00734b"
      }
    ],
    "suggestion": "",
    "additionalDishes": [
      "Donovans · Chicken Liver 鸡肝酱配面包"
    ],
    "recommendationNote": "Donovans：食客推荐鸡肝酱涂面包吃，整体口味偏淡。来自 2025 年探店，供晚餐备选时参考。"
  }
}
